### ISSUE TITLE
unicode is not defined

### ISSUE THREAD

**Issue by ianjosephwilson** [formencode/formencode#104]
This line seems to be fixed, or ignored with `if str is not str`, when I install 1.0.3a1 but it still seems to be in master and also in the 1.0.3a1 tagged branch.  I'm using python3.3.

https://github.com/formencode/formencode/blob/master/formencode/api.py#L153
https://github.com/formencode/formencode/blob/1.3.0a1/formencode/api.py#L153

```
Starting subprocess with file monitor
Traceback (most recent call last):
  File "../ve/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/user/workspace/project-container/myproject/myproject/myproject/__init__.py", line 165, in main
    config.scan('myproject.views')
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/pyramid/config/__init__.py", line 930, in scan
    ignore=ignore)
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/home/user/workspace/project-container/myproject/myproject/myproject/views/api.py", line 19, in <module>
    from formencode import (
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/formencode/__init__.py", line 3, in <module>
    from formencode.api import (
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/formencode/api.py", line 109, in <module>
    class Invalid(Exception):
  File "/home/user/workspace/project-container/myproject/ve/lib/python3.3/site-packages/formencode/api.py", line 153, in Invalid
    if unicode is not str:  # Python 2
NameError: name 'unicode' is not defined
```

When I install FormEncode-1.3.0a1 with pip install the code looks like this:

```
    if str is not str:  # Python 2

        def __unicode__(self):
            if isinstance(self.msg, str):
                return self.msg
            elif isinstance(self.msg, str):
                return self.msg.decode('utf8')
            else:
                return str(self.msg)
```

**Comment by lambacck** [comment]
Looks like an oversight in the removal of the 2to3 path. I'll use six to do that condition and look for similar checks.

**Comment by lambacck** [comment]
Oops, sorry. This will be fixed when we merge the 2to3 removal branch. You are running into a problem because there is no 2to3 step being run possibly because of a cached wheel?

**Comment by ianjosephwilson** [comment]
Just to be clear, it works for me if I use formencode 1.3a1 so for my purposes its "fixed" by just installing the alpha version and bumping my `requirements.txt` file.  The only thing that was weird to me was that I removed and recreated my virtualenv for a project with formencode in it and then re-initialized the virtualenv with `pip install -r requirements.txt` and suddenly there was a blocking formencode exception when the setup should have been exactly the same as before.  Still happens now if I just `pip install formencode` into a fresh virtualenv.  Is formencode 1.3 not compatible with python3 but only 1.3a1 is?  How would I know if I had a cached wheel?

```
ian@icecreamsandwich ~/workspace $ mkdir fe-test
ian@icecreamsandwich ~/workspace $ cd fe-test
ian@icecreamsandwich ~/workspace/fe-test $ virtualenv -p python3 --no-site-packages ve
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in ve/bin/python3
Also creating executable in ve/bin/python
Installing setuptools, pip, wheel...
done.
ian@icecreamsandwich ~/workspace/fe-test $ ve/bin/pip install formencode
Collecting formencode
Installing collected packages: formencode
Successfully installed formencode-1.3.0
ian@icecreamsandwich ~/workspace/fe-test $ ve/bin/python
Python 3.3.5 (default, Nov  2 2015, 08:17:12) 
[GCC 4.8.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import formencode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ian/workspace/fe-test/ve/lib/python3.3/site-packages/formencode/__init__.py", line 3, in <module>
    from formencode.api import (
  File "/home/ian/workspace/fe-test/ve/lib/python3.3/site-packages/formencode/api.py", line 109, in <module>
    class Invalid(Exception):
  File "/home/ian/workspace/fe-test/ve/lib/python3.3/site-packages/formencode/api.py", line 153, in Invalid
    if unicode is not str:  # Python 2
NameError: name 'unicode' is not defined
>>> 
```

**Comment by lambacck** [comment]
If you install to python 2 and then install to python 3 then with recent pip you will have cached wheels that are not compatible to with python 3 because of https://github.com/formencode/formencode/blob/master/setup.cfg#L29 being set to 1 instead of 0. Next version will not require 2to3 so universal wheel will work.

**Comment by lambacck** [comment]
This is fixed by #103

**Comment by bittner** [comment]
Can we have a new release (looks like 2.0.0 is in the making) because I'm hitting this issue with Python 3.4.3 in a Pyramid project. The installation off the GitHub repo seems to be working and resolve the Python 2 vs. 3 (`unicode`) issue:
``` bash
$ pip install git+https://github.com/formencode/formencode.git#egg=FormEncode
```

**Comment by sigmavirus24** [comment]
Hey @lambacck thanks for FormEncode! Users of SQLObject on Python 3 (which relies on FormEncode) are running into this with 1.3.0. Is there any chance a new release could be made, perhaps a 1.3.1 or something? Thanks in advance!
