### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by avanov** [formencode/formencode#2]
There are only two packages in my toolchain that prevent me from moving onto Python 3 - PIL and FormEncode. Therefore, I'd like to help you to migrate the codebase to Py3K and do it as soon as possible. What obstacles do you have on the way for now?

**Comment by GevatterGaul** [comment]
We use this now for about a year with Python 3 on our website on all forms. We got no Python 3 related issues up to date.

**Comment by pythonishvili** [comment]
Hello I encountered an issue that seems to be relevant for this ticket.

```
Python 3.4.3 (default, Jul 24 2015, 14:27:56) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import formencode.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/remy/.virtualenvs/venv/lib/python3.4/site-packages/formencode/__init__.py", line 3, in <module>
    from formencode.api import (
  File "/home/remy/.virtualenvs/venv/lib/python3.4/site-packages/formencode/api.py", line 109, in <module>
    class Invalid(Exception):
  File "/home/remy/.virtualenvs/venv/lib/python3.4/site-packages/formencode/api.py", line 153, in Invalid
    if unicode is not str:  # Python 2
NameError: name 'unicode' is not defined
```

Is the 1.3.0 version really compatible with Python 3.x and I am doing something wrong? Thanks.

**Comment by Cito** [comment]
You're doing something wrong. If Formencode 1.3.0 had been installed properly e.g. with `python3 setup.py install` or `pip install formencode`, then the 2to3 mechanism should have translated the `unicode` in line 153 above into `str`, so the line should read `if str is not str`.

**Comment by pythonishvili** [comment]
Yes, I was spectacularly wrong! I forgot that I had pip global index-url set to a private cheeseshop and there happened to be a formencode 1.3.0 wheel which I didn't notice during first installation. Thanks.

**Comment by antoniojesvs** [comment]
Using Pyramid and Python 3.4.
When I leave an <input type="file" name="file">... empty, the request.POST has {'file': b' '}.
b' ' is iterable, so formencode raises singleValueExpected=_('Please provide only one value')

Am I doing something wrong?

**Comment by lambacck** [comment]
@antoniojesvs can you please file this as a new issue. This means that we're interpreting the value as some non-string sequence. I suspect there needs to be some handling of a difference between python 2 and 3 here. As a workaround you can try adding ```accept_iterator=True``` to the constructor of your ```FieldStorageUploadConverter```.

**Comment by deeTEEcee** [comment]
hmm, UnicodeString/String still forces bytes when i use `from_python`...

**Comment by jvanasco** [comment]
FYI: if using  a `FieldStorageUploadConverter`, you should close the underlying file pointer in a cleanup function

    import webob.compat
    def _form_cleanup(request):
        # assumes the form is on `request.form`
        for (k, v) in list(request.form.results.items()):
            try:
                # don't compare to Boolean, as some Form objects can't handle that
                if isinstance(v, webob.compat.cgi_FieldStorage):
                    v.fp.close()
            except Exception as exc:
                pass

    request.add_finished_callback(_form_cleanup)
