### ISSUE TITLE
Can't use field named 'fields' in Schema

### ISSUE THREAD

**Issue by cecton** [formencode/formencode#30]
Hello,

```
>>> formencode.schema.Schema(fields=formencode.validators.String())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python2.7/site-packages/formencode/api.py", line 217, in __init__
    declarative.Declarative.__init__(self, *args, **kw)
  File "lib/python2.7/site-packages/formencode/declarative.py", line 150, in __init__
    self.__initargs__(kw)
  File "lib/python2.7/site-packages/formencode/schema.py", line 117, in __initargs__
    self.fields[key] = value
TypeError: 'String' object does not support item assignment
```

It breaks also with the class syntax.

**Comment by cecton** [comment]
Inactive, closing
