### ISSUE TITLE
failures in testsuite, -1.3.0; FAILED (errors=2, failures=3)

### ISSUE THREAD

**Issue by idella** [formencode/formencode#78]
Cannot find any history of failures in testsuite in previous issues.
Under py2.7

```python
======================================================================
ERROR: formencode.tests.test_doctests.test_doctests('/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/docs/htmlfill.txt', False, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_doctests.py", line 69, in _wrapper
    fn(*a_test_args)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_doctests.py", line 51, in doctest_file
    verbose=verbose)
  File "/usr/lib64/python2.7/doctest.py", line 2035, in testfile
    test = parser.get_doctest(text, globs, name, filename, 0)
  File "/usr/lib64/python2.7/doctest.py", line 671, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/usr/lib64/python2.7/doctest.py", line 685, in get_examples
    return [x for x in self.parse(string, name)
  File "/usr/lib64/python2.7/doctest.py", line 647, in parse
    self._parse_example(m, name, lineno)
  File "/usr/lib64/python2.7/doctest.py", line 717, in _parse_example
    lineno + len(source_lines))
  File "/usr/lib64/python2.7/doctest.py", line 803, in _check_prefix
    (lineno+i+1, name, line))
ValueError: line 4 of the docstring for htmlfill.txt has inconsistent leading whitespace: '\r'

======================================================================
ERROR: formencode.tests.test_doctests.test_doctests('/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/docs/Validator.txt', False, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_doctests.py", line 69, in _wrapper
    fn(*a_test_args)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_doctests.py", line 51, in doctest_file
    verbose=verbose)
  File "/usr/lib64/python2.7/doctest.py", line 2035, in testfile
    test = parser.get_doctest(text, globs, name, filename, 0)
  File "/usr/lib64/python2.7/doctest.py", line 671, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/usr/lib64/python2.7/doctest.py", line 685, in get_examples
    return [x for x in self.parse(string, name)
  File "/usr/lib64/python2.7/doctest.py", line 647, in parse
    self._parse_example(m, name, lineno)
  File "/usr/lib64/python2.7/doctest.py", line 717, in _parse_example
    lineno + len(source_lines))
  File "/usr/lib64/python2.7/doctest.py", line 803, in _check_prefix
    (lineno+i+1, name, line))
ValueError: line 5 of the docstring for Validator.txt has inconsistent leading whitespace: '\r'
```

then

 ```python
======================================================================
FAIL: formencode.tests.test_doctests.test_doctests('/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/non_empty.txt', False, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_doctests.py", line 69, in _wrapper
    fn(*a_test_args)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_doctests.py", line 54, in doctest_file
    assert failure_count == 0
AssertionError: 
```

for the sake of saving space, 
File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/non_empty.txt", line 7, in non_empty.txt
Failed example:

most every element in this file non_empty.txt fails, culminating in

```python
1 items had failures:
  16 of  40 in non_empty.txt
***Test Failed*** 16 failures.

--------------------- >> end captured stdout << ----------------------
    assert 40 > 0
>>  assert 16 == 0
```

finally

```python
======================================================================
FAIL: formencode.tests.test_htmlfill.test_inputoutput('/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/htmlfill_data/data-error1.txt',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_htmlfill.py", line 79, in run_filename
    assert False
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
---- Output:   ----
<form>
<test!>


!!!&lt;HEY&gt;!!!

<input type="text" name="t1" class="error" value="">

<span class="error-message">&lt;error</span><br />

<select name="t2" class="error">
<option value="1">1</option>
<option value="2">2</option>
</select>

<span class="error-message">last</span><br />

<textarea name="t3" class="error"></textarea>




---- Expected: ----

<form>
<test!>


!!!&lt;HEY&gt;!!!

<input type="text" name="t1" class="error" value="">

<span class="error-message">&lt;error</span><br />

<select name="t2" class="error">
<option value="1">1</option>
<option value="2">2</option>
</select>

<span class="error-message">last</span><br />

<textarea name="t3" class="error"></textarea>


--------------------- >> end captured stdout << ----------------------
    print '<form>\r\n<test!>\r\n\r\n\r\n!!!&lt;HEY&gt;!!!\r\n\r\n<input type="text" name="t1" class="error" value="">\r\n\r\n<span class="error-message">&lt;error</span><br />\n\r\n<select name="t2" class="error">\r\n<option value="1">1</option>\r\n<option value="2">2</option>\r\n</select>\r\n\r\n<span class="error-message">last</span><br />\n\r\n<textarea name="t3" class="error"></textarea>\r\n\r\n\r\n\r\n'
    print '---- Expected: ----'
    print '\r\n<form>\r\n<test!>\r\n\r\n\r\n!!!&lt;HEY&gt;!!!\r\n\r\n<input type="text" name="t1" class="error" value="">\r\n\r\n<span class="error-message">&lt;error</span><br />\r\n\r\n<select name="t2" class="error">\r\n<option value="1">1</option>\r\n<option value="2">2</option>\r\n</select>\r\n\r\n<span class="error-message">last</span><br />\r\n\r\n<textarea name="t3" class="error"></textarea>\r\n'
>>  assert False
    

======================================================================
FAIL: formencode.tests.test_htmlfill.test_inputoutput('/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/htmlfill_data/data-fill4.txt',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0/formencode/tests/test_htmlfill.py", line 79, in run_filename
    assert False
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
---- Output:   ----
<form>
<input type="text" name="name" value="Bob Jones">
<select name="occupation" multiple="multiple">
 <option value="">Default</option>
 <option value="Crazy Cultist" selected="selected">Crazy cultist</option>
 <option value="Crazy" selected="selected">Crazy</option>
</select>
<textarea cols="20" style="width: 100%" name="address">14 W. Canal
New Guinea</textarea>
<input type="radio" name="living" value="yes">
<input type="radio" name="living" value="no" checked="checked">
<input type="checkbox" name="nice_guy">

---- Expected: ----

<form>
<input type="text" name="name" value="Bob Jones">
<select name="occupation" multiple="multiple">
 <option value="">Default</option>
 <option value="Crazy Cultist" selected="selected">Crazy cultist</option>
 <option value="Crazy" selected="selected">Crazy</option>
</select>
<textarea cols="20" style="width: 100%" name="address">14 W. Canal
New Guinea</textarea>
<input type="radio" name="living" value="yes">
<input type="radio" name="living" value="no" checked="checked">
<input type="checkbox" name="nice_guy">


--------------------- >> end captured stdout << ----------------------
    print '<form>\r\n<input type="text" name="name" value="Bob Jones">\r\n<select name="occupation" multiple="multiple">\r\n <option value="">Default</option>\r\n <option value="Crazy Cultist" selected="selected">Crazy cultist</option>\r\n <option value="Crazy" selected="selected">Crazy</option>\r\n</select>\r\n<textarea cols="20" style="width: 100%" name="address">14 W. Canal\nNew Guinea</textarea>\r\n<input type="radio" name="living" value="yes">\r\n<input type="radio" name="living" value="no" checked="checked">\r\n<input type="checkbox" name="nice_guy">\r\n'
    print '---- Expected: ----'
    print '\r\n<form>\r\n<input type="text" name="name" value="Bob Jones">\r\n<select name="occupation" multiple="multiple">\r\n <option value="">Default</option>\r\n <option value="Crazy Cultist" selected="selected">Crazy cultist</option>\r\n <option value="Crazy" selected="selected">Crazy</option>\r\n</select>\r\n<textarea cols="20" style="width: 100%" name="address">14 W. Canal\r\nNew Guinea</textarea>\r\n<input type="radio" name="living" value="yes">\r\n<input type="radio" name="living" value="no" checked="checked">\r\n<input type="checkbox" name="nice_guy">\r\n'
>>  assert False
    

----------------------------------------------------------------------
Ran 259 tests in 2.755s

FAILED (errors=2, failures=3)
```

for py3, the whole suite fails due to incompatibility or something wrong with pycountry, or is it?

```python
======================================================================
ERROR: Failure: DistributionNotFound (FormEncode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib64/python3.3/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib64/python3.3/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib64/python3.3/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.3/imp.py", line 190, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.3/imp.py", line 160, in load_package
    return _bootstrap.SourceFileLoader(name, path).load_module(name)
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/mnt/gen2/TmpDir/portage/dev-python/formencode-1.3.0/work/FormEncode-1.3.0-python3_3/lib/formencode/tests/__init__.py", line 16, in <module>
    pkg_resources.require('FormEncode')
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.3/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
nose.proxy.DistributionNotFound: FormEncode
```

It appears it is seeking FormEncode rather than formencode.  No idea how that occurs.

**Comment by idella** [comment]
apparently this package need be system installed to even run the testsuite. This undermines everything above.

**Comment by lambacck** [comment]
For python3 support is provided by 2to3 so I think you need to install it to make it work. We run the tests using [tox](https://tox.readthedocs.org/en/latest/), I'm not sure I've run the tests not under tox in more than a year and that is how the tests are run in the TravisCI environment.

**Comment by lambacck** [comment]
Travis CI test run details can be found here: https://travis-ci.org/formencode/formencode

**Comment by idella** [comment]
this is unresolvable in gentoo. The tarball can be improved by adding the tox.ini
